export const language = {
    'af':' Afrikaans',
    'al':' Albanian',
    'ar':' Arabic',
    'az':' Azerbaijani',
    'bg':' Bulgarian',
    'ca':' Catalan',
    'cz':' Czech',
    'da':' Danish',
    'de':' German',
    'el':' Greek',
    'en':' English',
    'eu':' Basque',
    'fa':' Persian (Farsi)',
    'fi':' Finnish',
    'fr':' French',
    'gl':' Galician',
    'he':' Hebrew',
    'hi':' Hindi',
    'hr':' Croatian',
    'hu':' Hungarian',
    'id':' Indonesian',
    'it':' Italian',
    'ja':' Japanese',
    'kr':' Korean',
    'la':' Latvian',
    'lt':' Lithuanian',
    'mk':' Macedonian',
    'no':' Norwegian',
    'nl':' Dutch',
    'pl':' Polish',
    'pt':' Portuguese',
    'pt':'Português Brasil',
    'ro':' Romanian',
    'ru':' Russian',
    'sv':'Swedish',
    'sk':' Slovak',
    'sl':' Slovenian',
    'sp':'Spanish',
    'sr':' Serbian',
    'th':' Thai',
    'tr':' Turkish',
    'ua':'Ukrainian',
    'vi':' Vietnamese',
    'zh':'Chinese Simplified',
    'zh':'Chinese Traditional',
    'zu':' Zulu',
};

export const weatherConditions = {
    'clear sky': [800],
    'few clouds': [801],
    'scattered clouds': [802],
    'overcast clouds': [804],
    'broken clouds': [803],
    'shower rain': [313, 314, 520, 521, 522, 531],
    'rain': [501, 502, 503, 504, 511, 520, 521, 522, 531],
    'light rain': [500],
    'thunderstorm': [200, 201, 202, 210, 211, 212, 221, 230, 231, 231],
    'snow': [600, 601, 602, 611, 612, 613, 615, 616, 620, 621, 622],
    'mist': [701, 711, 721, 731, 741, 751, 761, 762, 771, 781]
};

export const weatherIcons = {
    'clear sky': 'https://www.linkpicture.com/q/clearsky.png',
    'few clouds': 'https://cdn3.iconfinder.com/data/icons/tango-icon-library/48/weather-few-clouds-night-256.png',
    'scattered clouds': 'https://www.linkpicture.com/q/scattered_cloud_new.png',
    'overcast clouds': 'https://cdn4.iconfinder.com/data/icons/iconsland-weather/PNG/256x256/Overcast.png',
    'broken clouds': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKm05o0_4KDgZ2mFikxxvyfMy4mbvU_zrXKyfxfQ21zOcDaT5Y89KaTlQlODgOBWp3FpU&usqp=CAU',
    'shower rain': 'https://cdn4.iconfinder.com/data/icons/iconsland-weather/PNG/256x256/Hail_Heavy.png',
    'rain': 'https://cdn4.iconfinder.com/data/icons/iconsland-weather/PNG/256x256/Night_Rain.png',
    'light rain': 'https://cdn4.iconfinder.com/data/icons/the-weather-is-nice-today/64/weather_7-256.png',
    'thunderstorm': 'https://cdn4.iconfinder.com/data/icons/the-weather-is-nice-today/64/weather_24-256.png',
    'snow': 'https://cdn4.iconfinder.com/data/icons/weather-29/256/cloud_snow-256.png',
    'mist': 'https://cdn4.iconfinder.com/data/icons/the-weather-is-nice-today/64/weather_38-256.png'
};